spring:
  sql:
    init:
      mode: always
  datasource:
    username: sa
    url: jdbc:h2:mem:shareit
    driverClassName: org.h2.Driver
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
  config:
    activate:
      on-profile: ci,test
logging:
  level:
    org:
      springframework:
        transaction:
          nodeValue: INFO
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
